from ubique.brain.runtime import NeurocognitiveRuntime


def test_only_library_sources_and_real_experiments_ground_stances():
    records = [
        {"epistemic_status": "external_source", "source": "library:darwin"},
        {"epistemic_status": "observed_action_outcome", "source": "action:experiment"},
        {"epistemic_status": "observed_action_outcome", "source": "action:library"},
        {"epistemic_status": "observed_action_outcome", "source": "action:consolidate"},
        {"epistemic_status": "observed_history", "source": "runtime"},
    ]
    assert NeurocognitiveRuntime._stance_grounding_sources(records) == [
        "external_source:library:darwin",
        "observed_action_outcome:action:experiment",
    ]


def test_explicit_relevant_library_episode_validates_stance():
    evidence = [{
        "id": "episode:darwin",
        "epistemic_status": "external_source",
        "source": "library:darwin",
        "text": "Emotional expressions in humans and animals show inherited patterns and evolutionary continuity.",
        "concepts": ["emotion", "expression", "evolution"],
    }]
    updates = [{
        "topic": "nature of emotion",
        "position": "Some emotional expression has an evolutionary history.",
        "reasoning": "The passage compares inherited emotional expressions across species.",
        "confidence": 0.7,
        "relation": "new",
        "evidence_ids": ["episode:darwin"],
    }]
    result = NeurocognitiveRuntime._validate_stance_updates(updates, evidence)
    assert result[0]["validated_evidence_ids"] == ["episode:darwin"]


def test_unrelated_book_cannot_ground_stance_merely_by_being_present():
    evidence = [{
        "id": "episode:ethics",
        "epistemic_status": "external_source",
        "source": "library:aristotle",
        "text": "Virtue concerns habits of action and character in pursuit of the good.",
        "concepts": ["virtue", "ethics", "habit"],
    }]
    updates = [{
        "topic": "nature of consciousness",
        "position": "Consciousness is generated by recurrent neural processing.",
        "reasoning": "A neural account seems plausible.",
        "confidence": 0.8,
        "relation": "new",
        "evidence_ids": ["episode:ethics"],
    }]
    assert NeurocognitiveRuntime._validate_stance_updates(updates, evidence) == []


def test_issue_text_and_lifecycle_cannot_ground_personality():
    records = [
        {"epistemic_status": "observed_external_input", "source": "github:user"},
        {"epistemic_status": "observed_external_state", "source": "github:lifecycle"},
    ]
    assert NeurocognitiveRuntime._stance_grounding_sources(records) == []
